---
name: CGI-Auth-Basic
version: 1.21
author:
  - 'Burak Gursoy <burak@cpan.org>'
abstract: Basic CGI authentication interface.
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/burak/cpan-cgi-auth-basic/
build_requires:
  Test::More: 0.40
provides:
  CGI::Auth::Basic:
    file: lib/CGI/Auth/Basic.pm
    version: 1.21
no_index:
  directory:
    - monolithic_version
    - builder
    - t
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
